export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const FAILURE = 'FAILURE';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
